#ifndef ERRORSIGNALS_H
#define ERRORSIGNALS_H

enum Error_signal {
    INCORRECT_ID,
    NO_SEMESTERS,
    INCORRECT_GENDER,
    INCORRECT_YES_NO_ANSWER,
    CANT_REGISTER_TO_COURSE,
    UNKNOWN_COMMAND,
    COURSE_HAS_NO_SEMESTER, 
    COURSE_NOT_IN_SEMESTER,
    OPEN_FILE_ERROR,
    COURSE_NOT_IN_CURRENT_SEASON,
    HAS_ENDED,
    STRING_INSTEAD_OF_INTEGER
};

#endif